#!/bin/sh
sv check dbus >/dev/null || exit 1

#OPTS='--log-file=/dev/null' # disable all logging by default
OPTS='--test-quick-suspend-resume' # use quick suspend/resume hooks
DUAL_SIM=true
[ -r conf ] && . ./conf
if grep -q 'qcom,' /proc/device-tree/compatible 2>/dev/null; then
	sv check rmtfs >/dev/null || exit 1

	ipa_sysfs="/sys/bus/platform/drivers/ipa"
	[ -d "$ipa_sysfs" ] || exit 1

	qmicli="qmicli -d qrtr://0 -p"
	# TODO: can we just always run this and not gate behind having DUAL_SIM set?!
	if [ -n "$DUAL_SIM" ]; then
		# https://gitlab.freedesktop.org/mobile-broadband/ModemManager/-/issues/649
		: ${AID:=$($qmicli --uim-get-card-status | grep -E "([A-Z0-9]{2}:){15}[A-Z0-9]{2}" | xargs)}
		[ "$AID" ] || exit 1
		$qmicli --uim-change-provisioning-session="slot=1,activate=yes,session-type=primary-gw-provisioning,aid=$AID" >/dev/null
	fi
fi

exec ModemManager $OPTS
