#!/bin/sh
sv check dbus >/dev/null || exit 1
if [ -e /var/service/rmtfs ]; then
	sv check rmtfs >/dev/null || exit 1
fi

#OPTS='--log-file=/dev/null' # disable all logging by default
[ -r conf ] && . ./conf
if [ -r /proc/device-tree/compatible ] && grep -q 'qcom,' /proc/device-tree/compatible; then
	qmicli="qmicli -d qrtr://0 -p"
	if [ -n "$DUAL_SIM" ]; then
		: ${AID:=$($qmicli --uim-get-card-status | grep -E "([A-Z0-9]{2}:){15}[A-Z0-9]{2}" | xargs)}
		[ "$AID" ] || exit 1
		$qmicli --uim-change-provisioning-session="slot=1,activate=yes,session-type=primary-gw-provisioning,aid=$AID" >/dev/null
	fi

	IPA_SYSFS="/sys/bus/platform/drivers/ipa"
	[ -d "$IPA_SYSFS" ] || exit 1
	MODEM_TX_EP=$(cat $IPA_SYSFS/*.ipa/modem/tx_endpoint_id) # e.g. 3 for 8998, 2 for 835
	MODEM_RX_EP=$(cat $IPA_SYSFS/*.ipa/modem/rx_endpoint_id) # e.g. 16 for 8998, 10 for 845
	$qmicli --dpm-open-port="hw-data-ep-type=embedded,hw-data-ep-iface-number=1,hw-data-rx-id=$MODEM_TX_EP,hw-data-tx-id=$MODEM_RX_EP" >/dev/null || exit 1
fi

exec ModemManager $OPTS
