#!/bin/sh
sv check dbus >/dev/null || exit 1
if [ -e /var/service/rmtfs ]; then
	sv check rmtfs >/dev/null || exit 1
fi

#ARGS='--log-file=/dev/null'
DUAL_SIM=false
[ -r conf ] && . ./conf

if $DUAL_SIM; then
	AID=${AID:-$(qmicli -d qrtr://0 -p --uim-get-card-status | grep -E "([A-Z0-9]{2}:){15}[A-Z0-9]{2}" | xargs)}
	[ "$AID" ] || exit 1
	qmicli -d qrtr://0 -p --uim-change-provisioning-session="slot=1,activate=yes,session-type=primary-gw-provisioning,aid=$AID" >/dev/null
fi

if [ "$DPM_RX_ID" ] && [ "$DPM_TX_ID" ]; then
	qmicli -d qrtr://0 -p --dpm-open-port="hw-data-ep-type=embedded,hw-data-ep-iface-number=1,hw-data-rx-id=$DPM_RX_ID,hw-data-tx-id=$DPM_TX_ID" >/dev/null || exit 1
fi

exec ModemManager $ARGS
